"""Compatibility re-export of shared phase execution contracts."""

from rs.scheduling.phase_execution import (
    AbstractPhaseExecutionPlan,
    AbstractPlanWave,
    AbstractTaskRef,
    BucketTask,
    FutureDemandHint,
    IncomingSlot,
    OutgoingSegment,
    PackedTensorDescriptor,
    PayloadSlice,
    PhaseExecutionPlan,
    PhaseHookResult,
    PhaseName,
    PhasePlanningSummary,
    PhaseReadyContext,
    PlanWave,
    TransferLayout,
    TransportBundle,
)

__all__ = [
    "BucketTask",
    "AbstractPhaseExecutionPlan",
    "AbstractPlanWave",
    "AbstractTaskRef",
    "FutureDemandHint",
    "IncomingSlot",
    "OutgoingSegment",
    "PackedTensorDescriptor",
    "PayloadSlice",
    "PhaseExecutionPlan",
    "PhaseHookResult",
    "PhaseName",
    "PhasePlanningSummary",
    "PhaseReadyContext",
    "PlanWave",
    "TransferLayout",
    "TransportBundle",
]
