from __future__ import annotations

from typing import Any


def build_prepared_plan_summary(*, runtime_state: Any) -> dict[str, Any]:
    active_prediction = runtime_state.read("active_next_dispatch_prediction") or {}
    consumption_records = list(runtime_state.read("prediction_consumption_records", []) or [])
    global_joint_window_plan = runtime_state.read("global_joint_window_plan") or {}
    return {
        "has_prepared_plan": bool(runtime_state.read("prepared_plan") is not None),
        "plan_source_layer": str(runtime_state.read("plan_source_layer", "")),
        "plan_created_at_us": int(runtime_state.read("plan_created_at_us", 0) or 0),
        "p2_matrix_source": str(runtime_state.read("p2_matrix_source", "")),
        "p2_matrix_total_bytes": int(runtime_state.read("p2_matrix_total_bytes", 0) or 0),
        "p2_matrix_row_sums": list(runtime_state.read("p2_matrix_row_sums", []) or []),
        "p2_matrix_col_sums": list(runtime_state.read("p2_matrix_col_sums", []) or []),
        "p2_matrix_is_replicated_local_row": bool(runtime_state.read("p2_matrix_is_replicated_local_row", False)),
        "p2_matrix_shape": list(runtime_state.read("p2_matrix_shape", []) or []),
        "p2_matrix_gather_time_us": float(runtime_state.read("p2_matrix_gather_time_us", 0.0) or 0.0),
        "p2_matrix_gather_status": str(runtime_state.read("p2_matrix_gather_status", "")),
        "p2_matrix_gather_call_count": int(runtime_state.read("p2_matrix_gather_call_count", 0) or 0),
        "predictor_name": str(runtime_state.read("predictor_name", "")),
        "prediction_digest": str(runtime_state.read("prediction_digest", "")),
        "prediction_confidence": float(runtime_state.read("prediction_confidence", 0.0) or 0.0),
        "planning_traffic_source": str(runtime_state.read("planning_traffic_source", "")),
        "pre_transport_observation_valid": bool(runtime_state.read("pre_transport_observation_valid", False)),
        "captured_before_transport": bool(runtime_state.read("captured_before_transport", False)),
        "dispatcher_send_splits": list(runtime_state.read("dispatcher_send_splits", ()) or ()),
        "dispatcher_recv_splits": list(runtime_state.read("dispatcher_recv_splits", ()) or ()),
        "local_p0_row": list(runtime_state.read("local_p0_row", ()) or ()),
        "actual_p0_total_rows": int(runtime_state.read("actual_p0_total_rows", 0) or 0),
        "p0_traffic_matrix_gather_count": int(runtime_state.read("p0_traffic_matrix_gather_count", 0) or 0),
        "prediction_extra_collective_count": int(runtime_state.read("prediction_extra_collective_count", 0) or 0),
        "p1_planning_collective_count": int(runtime_state.read("p1_planning_collective_count", 0) or 0),
        "before_async_p2p_phase_count": int(runtime_state.read("before_async_p2p_phase_count", 0) or 0),
        "after_async_p2p_phase_count": int(runtime_state.read("after_async_p2p_phase_count", 0) or 0),
        "selected_layer_before_async_p2p_phase_count": int(runtime_state.read("selected_layer_before_async_p2p_phase_count", 0) or 0),
        "selected_layer_after_async_p2p_phase_count": int(runtime_state.read("selected_layer_after_async_p2p_phase_count", 0) or 0),
        "all_layer_async_phase_count": int(runtime_state.read("all_layer_async_phase_count", 0) or 0),
        "stored_p1_plan_digest": str(runtime_state.read("stored_p1_plan_digest", "")),
        "consumed_p1_plan_digest": str(runtime_state.read("consumed_p1_plan_digest", "")),
        "compiler_id": str(runtime_state.read("compiler_id", "")),
        "logical_plan_digest": str(runtime_state.read("logical_plan_digest", "")),
        "compiled_plan_digest": str(runtime_state.read("compiled_plan_digest", "")),
        "canonical_task_digest": str(runtime_state.read("canonical_task_digest", "")),
        "canonical_task_count": int(runtime_state.read("canonical_task_count", 0) or 0),
        "canonical_task_total_rows": int(runtime_state.read("canonical_task_total_rows", 0) or 0),
        "compiler_shadow_status": str(runtime_state.read("compiler_shadow_status", "")),
        "compiler_shadow_plan_hash_matches_legacy": bool(runtime_state.read("compiler_shadow_plan_hash_matches_legacy", False)),
        "compiler_shadow_plan_hash": str(runtime_state.read("compiler_shadow_plan_hash", "")),
        "compiler_shadow_missing_task_count": int(runtime_state.read("compiler_shadow_missing_task_count", 0) or 0),
        "compiler_shadow_extra_task_count": int(runtime_state.read("compiler_shadow_extra_task_count", 0) or 0),
        "compiler_shadow_execution_order_matches_legacy": bool(runtime_state.read("compiler_shadow_execution_order_matches_legacy", False)),
        "legacy_secondary_policy_invocation_count": int(runtime_state.read("legacy_secondary_policy_invocation_count", 0) or 0),
        "dispatch_transport_start_ns": int(runtime_state.read("dispatch_transport_start_ns", 0) or 0),
        "dispatch_transport_end_ns": int(runtime_state.read("dispatch_transport_end_ns", 0) or 0),
        "rank_release_ns": int(runtime_state.read("rank_release_ns", 0) or 0),
        "expert_compute_start_ns": int(runtime_state.read("expert_compute_start_ns", 0) or 0),
        "expert_compute_end_ns": int(runtime_state.read("expert_compute_end_ns", 0) or 0),
        "combine_transport_start_ns": int(runtime_state.read("combine_transport_start_ns", 0) or 0),
        "combine_transport_end_ns": int(runtime_state.read("combine_transport_end_ns", 0) or 0),
        "forward_start_ns": int(runtime_state.read("forward_start_ns", 0) or 0),
        "forward_end_ns": int(runtime_state.read("forward_end_ns", 0) or 0),
        "rank_release_lead_us": None,
        "expert_compute_start_lead_us": None,
        "communication_compute_overlap_us": None,
        "phase_barrier_wait_avoided_us": None,
        "critical_path_rank": None,
        "critical_path_forward_us": None,
        "active_prediction": dict(active_prediction),
        "prediction_created_stage": str(active_prediction.get("created_at_stage", "")),
        "prediction_source_layer": str(active_prediction.get("source_layer_id", "")),
        "prediction_target_layer": str(active_prediction.get("target_layer_id", "")),
        "prediction_first_consumed_stage": str(consumption_records[0].get("prediction_first_consumed_stage", "")) if consumption_records else "",
        "consumer_layer": str(consumption_records[0].get("consumer_layer", "")) if consumption_records else "",
        "consumer_phase": str(consumption_records[0].get("consumer_phase", "")) if consumption_records else "",
        "consumed_before_p1": bool(consumption_records[0].get("consumed_before_p1", False)) if consumption_records else False,
        "safe_selected_policy": str(global_joint_window_plan.get("safe_selected_policy", "")),
        "raw_u_policy_name": str(global_joint_window_plan.get("raw_u_policy_name", "")),
        "paired_b_policy_name": str(global_joint_window_plan.get("paired_b_policy_name", "")),
        "host_projected_estimated_makespan": float(runtime_state.read("host_projected_estimated_makespan", 0.0) or 0.0),
        "ideal_estimated_makespan": float(runtime_state.read("ideal_estimated_makespan", 0.0) or 0.0),
        "actual_p0_row_matrix": list(global_joint_window_plan.get("actual_p0_row_matrix", [])),
        "actual_p0_full_row_matrix": list(global_joint_window_plan.get("actual_p0_full_row_matrix", [])),
        "actual_p0_matrix_unit": "rows",
        "inferred_p1_row_matrix": list(global_joint_window_plan.get("inferred_p1_row_matrix", [])),
        "inferred_p1_remote_row_matrix": list(global_joint_window_plan.get("inferred_p1_remote_row_matrix", [])),
        "inferred_p1_matrix_unit": "rows",
        "p1_is_exact_transpose": bool(global_joint_window_plan.get("p1_is_exact_transpose", False)),
    }


__all__ = ["build_prepared_plan_summary"]
